name: CI
on: pull_request
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: npm ci
    - run: npm install
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        reporter: github-pr-review # Change reporter.
        eslint_flags: 'src/'
    # - name: Run ESLint
    #   run: npm run lint
