on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
jobs:
  steps:
    - name: hello workflow_dispatch
      run: echo hello
